"""add_taxon_group_to_taxon

Revision ID: 2ac96cb22a98
Revises: 95366f06d67d
Create Date: 2020-06-08 12:47:53.136175

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2ac96cb22a98"
down_revision = "95366f06d67d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("taxa", sa.Column("taxon_group", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("taxa", "taxon_group")
    # ### end Alembic commands ###
