"""remove additional_species_comments from taxa_crosswalk

Revision ID: 3f4b6b4b8076
Revises: 49966223fbab
Create Date: 2022-05-04 09:37:07.606072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4b6b4b8076'
down_revision = '49966223fbab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxa_crosswalk', 'additional_species_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxa_crosswalk', sa.Column('additional_species_comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
