"""change to verbatim_name

Revision ID: 49966223fbab
Revises: a1194f723b2e
Create Date: 2022-05-03 23:47:47.037119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49966223fbab'
down_revision = 'a1194f723b2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxa_crosswalk', 'original_name', new_column_name='verbatim_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxa_crosswalk', 'verbatim_name', new_column_name='original_name')
    # ### end Alembic commands ###
