"""move_aw_to_sections

Revision ID: 5a8de34b1085
Revises: 1e278257f346
Create Date: 2020-05-21 06:53:11.857038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5a8de34b1085"
down_revision = "1e278257f346"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("samples", "aw")
    op.add_column("sections", sa.Column("aw", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sections", "aw")
    op.add_column(
        "samples", sa.Column("aw", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
