"""empty message

Revision ID: 5c622754ebac
Revises: 3a1e01f96c2c
Create Date: 2020-05-18 17:08:31.669605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c622754ebac'
down_revision = '3a1e01f96c2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('holes', sa.Column('water_depth', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('holes', 'water_depth')
    # ### end Alembic commands ###
