"""move comments from taxon to taxon_crosswalk

Revision ID: 62ff80715d43
Revises: d24dd23aad7a
Create Date: 2021-04-13 18:51:27.038571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62ff80715d43'
down_revision = 'd24dd23aad7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxa', 'comments')
    op.add_column('taxa_crosswalk', sa.Column('comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('taxa_crosswalk', 'comments')
    op.add_column('taxa', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
