"""add original_taxa_id_to_taxa

Revision ID: 6938832cbce2
Revises: 24bc88e66a5b
Create Date: 2020-10-16 04:57:24.178833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6938832cbce2'
down_revision = '24bc88e66a5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples_taxa', sa.Column('original_taxon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'samples_taxa', 'taxa_crosswalk', ['original_taxon_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples_taxa', type_='foreignkey')
    op.drop_column('samples_taxa', 'original_taxon_id')
    # ### end Alembic commands ###
