"""add_index_on_eodp_id

Revision ID: 772be6b089a8
Revises: eaf7958d318d
Create Date: 2022-02-22 19:51:39.482328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '772be6b089a8'
down_revision = 'eaf7958d318d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_samples_eodp_id'), 'samples', ['eodp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samples_eodp_id'), table_name='samples')
    # ### end Alembic commands ###
