"""null taxon group for taxa

Revision ID: 80f1f642aec6
Revises: b564bb300483
Create Date: 2022-04-27 11:05:41.544044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f1f642aec6'
down_revision = 'b564bb300483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxa', 'taxon_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('taxa_crosswalk', 'taxon_group',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('taxa', 'taxon_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('taxa_crosswalk', 'taxon_group',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
