"""empty message

Revision ID: 8da23b838743
Revises: 12ab4670015f
Create Date: 2020-05-15 01:43:36.224047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da23b838743'
down_revision = '12ab4670015f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cores_name'), 'cores', ['name'], unique=False)
    op.create_index(op.f('ix_holes_name'), 'holes', ['name'], unique=False)
    op.create_index(op.f('ix_samples_name'), 'samples', ['name'], unique=False)
    op.create_index(op.f('ix_sections_name'), 'sections', ['name'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sections_name'), table_name='sections')
    op.drop_index(op.f('ix_samples_name'), table_name='samples')
    op.drop_index(op.f('ix_holes_name'), table_name='holes')
    op.drop_index(op.f('ix_cores_name'), table_name='cores')
    # ### end Alembic commands ###
