"""create expedition

Revision ID: 976c61dd8c89
Revises: 
Create Date: 2020-05-02 05:38:18.254134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976c61dd8c89'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expeditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('data_source_url', sa.String(), nullable=True),
    sa.Column('data_source_notes', sa.Text(), nullable=True),
    sa.Column('workbook_tab_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expeditions_name'), 'expeditions', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expeditions_name'), table_name='expeditions')
    op.drop_table('expeditions')
    # ### end Alembic commands ###
