"""add additional species comment

Revision ID: a1194f723b2e
Revises: d151b5cfba1e
Create Date: 2022-05-03 06:23:41.778814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1194f723b2e'
down_revision = 'd151b5cfba1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxa_crosswalk', sa.Column('additional_species_comments', sa.String(), nullable=True))
    op.add_column('taxa_crosswalk', sa.Column('comment', sa.String(), nullable=True))
    op.add_column('taxa_crosswalk', sa.Column('comments', sa.String(), nullable=True))
    op.drop_column('taxa_crosswalk', 'comments_2')
    op.drop_column('taxa_crosswalk', 'comments_1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxa_crosswalk', sa.Column('comments_1', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('taxa_crosswalk', sa.Column('comments_2', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('taxa_crosswalk', 'comments')
    op.drop_column('taxa_crosswalk', 'comment')
    op.drop_column('taxa_crosswalk', 'additional_species_comments')
    # ### end Alembic commands ###
