"""add data_source to SampleTaxon

Revision ID: a9c88584741a
Revises: aa5e16a8a2c6
Create Date: 2020-06-08 23:53:08.276411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c88584741a'
down_revision = 'aa5e16a8a2c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples_taxa', sa.Column('data_source_notes', sa.Text(), nullable=True))
    op.add_column('samples_taxa', sa.Column('data_source_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_samples_taxa_data_source_notes'), 'samples_taxa', ['data_source_notes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_samples_taxa_data_source_notes'), table_name='samples_taxa')
    op.drop_column('samples_taxa', 'data_source_url')
    op.drop_column('samples_taxa', 'data_source_notes')
    # ### end Alembic commands ###
