"""change top and bottom Sample to string

Revision ID: b025dca41f18
Revises: d74ea5a68cbb
Create Date: 2022-08-13 13:15:50.679757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b025dca41f18'
down_revision = 'd74ea5a68cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_samples_bottom', table_name='samples')
    op.drop_index('ix_samples_bottom_depth', table_name='samples')
    op.drop_index('ix_samples_top', table_name='samples')
    op.drop_index('ix_samples_top_depth', table_name='samples')
    op.alter_column('samples', 'top', existing_type=sa.Float(), type_=sa.String())
    op.alter_column('samples', 'bottom', existing_type=sa.Float(), type_=sa.String())
    op.alter_column('samples', 'top_depth', existing_type=sa.Float(), type_=sa.String())
    op.alter_column('samples', 'bottom_depth', existing_type=sa.Float(), type_=sa.String())

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('samples', 'top', existing_type=sa.String(), type_=sa.Float())
    op.alter_column('samples', 'bottom', existing_type=sa.String(), type_=sa.Float())
    op.alter_column('samples', 'top_depth', existing_type=sa.String(), type_=sa.Float())
    op.alter_column('samples', 'bottom_depth', existing_type=sa.String(), type_=sa.Float())
    op.create_index('ix_samples_top_depth', 'samples', ['top_depth'], unique=False)
    op.create_index('ix_samples_top', 'samples', ['top'], unique=False)
    op.create_index('ix_samples_bottom_depth', 'samples', ['bottom_depth'], unique=False)
    op.create_index('ix_samples_bottom', 'samples', ['bottom'], unique=False)
    # ### end Alembic commands ###
