"""add comments to samples taxa

Revision ID: b564bb300483
Revises: a69ae6a48ee0
Create Date: 2022-04-27 10:42:26.261971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b564bb300483'
down_revision = 'a69ae6a48ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxa_crosswalk', sa.Column('comments_1', sa.String(), nullable=True))
    op.add_column('taxa_crosswalk', sa.Column('comments_2', sa.String(), nullable=True))
    op.add_column('taxa_crosswalk', sa.Column('internal_notes', sa.String(), nullable=True))
    op.add_column('taxa_crosswalk', sa.Column('name_comment', sa.String(), nullable=True))
    op.drop_column('taxa_crosswalk', 'comments')
    op.drop_column('taxa_crosswalk', 'processing_notes')
    op.drop_column('taxa_crosswalk', 'initial_comments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxa_crosswalk', sa.Column('initial_comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('taxa_crosswalk', sa.Column('processing_notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('taxa_crosswalk', sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('taxa_crosswalk', 'name_comment')
    op.drop_column('taxa_crosswalk', 'internal_notes')
    op.drop_column('taxa_crosswalk', 'comments_2')
    op.drop_column('taxa_crosswalk', 'comments_1')

    # ### end Alembic commands ###
