"""add comments to samples_taxa

Revision ID: d151b5cfba1e
Revises: d7d6d4d6f9b1
Create Date: 2022-04-29 17:04:32.573665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd151b5cfba1e'
down_revision = 'd7d6d4d6f9b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples_taxa', sa.Column('comments', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples_taxa', 'comments')
    # ### end Alembic commands ###
