"""add eodp_id to taxa_crosswalk

Revision ID: d7d6d4d6f9b1
Revises: 80f1f642aec6
Create Date: 2022-04-28 16:01:26.632951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d6d4d6f9b1'
down_revision = '80f1f642aec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('taxa_crosswalk', sa.Column('eodp_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_taxa_crosswalk_eodp_id'), 'taxa_crosswalk', ['eodp_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_taxa_crosswalk_eodp_id'), table_name='taxa_crosswalk')
    op.drop_column('taxa_crosswalk', 'eodp_id')
    # ### end Alembic commands ###
