"""create abundance_crosswalk

Revision ID: dd97a1d782ad
Revises: 3f4b6b4b8076
Create Date: 2022-08-06 06:28:19.777371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd97a1d782ad'
down_revision = '3f4b6b4b8076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abundance_crosswalk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_abundance', sa.String(), nullable=False),
    sa.Column('normalized_abundance', sa.String(), nullable=True),
    sa.Column('expedition', sa.String(), nullable=False),
    sa.Column('taxon_group', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('definition', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abundance_crosswalk')
    # ### end Alembic commands ###
