"""name of migration

Revision ID: eff7b190e0de
Revises: b025dca41f18
Create Date: 2022-09-02 08:35:19.751369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eff7b190e0de'
down_revision = 'b025dca41f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('abundance_crosswalk')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abundance_crosswalk',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('original_abundance', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('normalized_abundance', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('expedition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('taxon_group', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('definition', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='abundance_crosswalk_pkey')
    )
    # ### end Alembic commands ###
